import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Sell-Safe Buy-Safe",
    short_name: "SBBS",
    description:
      "Ghana's protected checkout. SBBS holds the buyer's money safely until the goods arrive as promised.",
    start_url: "/",
    display: "standalone",
    background_color: "#FBFAFC",
    theme_color: "#4F2BB8",
    orientation: "portrait-primary",
    icons: [
      {
        // Generated by app/icon.tsx — 512x512 GSG pill on transparent canvas.
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        // Generated by app/apple-icon.tsx — 180x180 GSG pill on violet bg.
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
      {
        // Raw wide pill — useful for "maskable" / wider tiles.
        src: "/brand/fgfg.png",
        sizes: "931x470",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
